### PR TITLE
Suggested edits for openjournals/joss-reviews/issues/4562

### PR DESCRIPTION
**Pull request by thodson-usgs**

### CODE REVIEW

**Comment by ThomasThelen** [comment]
Thanks for the edits! I'm taking notes on those bibliography changes :)

I have two remarks that could use some clarification, otherwise I have no problem merging.

This project was done unfunded, so as far as traditional acknowledgements go, we don't have the normal NSF grant or university to thank. This was also a fairly self contained group that worked on this package without external collaboration, and I felt weird patting ourselves on the back. Would it be non-standard to leave this section out?

With the dependencies section, we were hoping to give credit to the other softwares that we used, similar to how [this](https://joss.theoj.org/papers/10.21105/joss.04039) paper did it. Is there any way we can keep it in?

**Comment by thodson-usgs** [comment]
Yes, I'm fine with both requests. If JOSS has precedent for including a dependencies section, then do so.

**Comment by ThomasThelen** [comment]
@thodson-usgs I'm not sure if I have permissions to edit your PR (I think there's a button for allowing editing access from maintainers, if I'm even one). Can you check to see if that box is checked on your PR?

Otherwise we should
- Remove the Acknowledgements section
- Re-add the Dependencies section
- Remove italics on `_require_` (when I was using `_must_` it was in the RFC definition sense)
- Remove the trailing comma on `properties ranging from simple constructs,` (I think it's a comma splice with the commas that follow)

**Comment by thodson-usgs** [comment]
@ThomasThelen 
Yes, I'm happy all with that.
Regarding:
"Remove italics on _require_ (when I was using _must_ it was in the RFC definition sense)"
I prefer require, but that's a reasonable reason to use must. When discussing functions, I think it's more common to discuss 'required' and 'optional' parameters.

As for merging, I think its simplest for you to make the edits manually, and  we close this PR. That's lame, I know, but I'm busy. I should be able to resume the review next week.

**Comment by ThomasThelen** [comment]
Not lame at all! I appreciate all of the effort you've put into this review and the PR.

**Comment by ThomasThelen** [comment]
Changes were made and merged in #87, to the `paper` branch. We appreciate the feedback and edits, thank you!

**Comment by ThomasThelen** [comment]
I ended up tracking the issue where I couldn't submit changes to the commit to my Ghostery plugin. I apologize for any inconveniences I caused there there

**Pull request closed without merging**
